-- Waigani Christian College: Supabase/PostgreSQL schema
-- Run this once in the Supabase SQL editor for a new project.

create extension if not exists pg_trgm;

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 3 and 160),
  summary text not null check (char_length(summary) between 5 and 400),
  body text not null default '' check (char_length(body) <= 10000),
  category text not null check (category in (
    'news_events', 'early_learning', 'primary_school',
    'secondary_school', 'student_life'
  )),
  event_date date,
  published boolean not null default true,
  promoted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.enquiries (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 120),
  email text not null check (char_length(email) <= 320),
  year_level text not null check (char_length(year_level) between 2 and 80),
  message text not null default '' check (char_length(message) <= 3000),
  status text not null default 'new' check (status in ('new', 'in_progress', 'resolved')),
  created_at timestamptz not null default now()
);

create index if not exists posts_public_order_idx
  on public.posts (published, promoted desc, event_date desc, created_at desc);
create index if not exists posts_category_idx on public.posts (category);
create index if not exists posts_search_idx
  on public.posts using gin ((title || ' ' || summary || ' ' || body) gin_trgm_ops);
create index if not exists enquiries_status_created_idx
  on public.enquiries (status, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists posts_set_updated_at on public.posts;
create trigger posts_set_updated_at
before update on public.posts
for each row execute function public.set_updated_at();

alter table public.posts enable row level security;
alter table public.enquiries enable row level security;

-- Visitors may only read published posts.
drop policy if exists "Public can read published posts" on public.posts;
create policy "Public can read published posts"
on public.posts for select
to anon, authenticated
using (published = true);

-- Visitors may submit an enquiry, but cannot read enquiry records.
drop policy if exists "Public can submit enquiries" on public.enquiries;
create policy "Public can submit enquiries"
on public.enquiries for insert
to anon, authenticated
with check (status = 'new');

-- The FastAPI server must use SUPABASE_SERVICE_ROLE_KEY for admin CRUD.
-- Never expose the service-role key in Vite or other browser code.

