-- Waigani Christian College: Supabase/PostgreSQL schema
-- Run this once in the Supabase SQL editor for a new project.

create extension if not exists pg_trgm;

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 3 and 160),
  summary text not null check (char_length(summary) between 5 and 400),
  body text not null default '' check (char_length(body) <= 10000),
  category text not null check (category in (
    'news_events', 'early_learning', 'primary_school',
    'secondary_school', 'student_life'
  )),
  event_date date,
  published boolean not null default true,
  promoted boolean not null default false,
  media_url text check (media_url is null or char_length(media_url) <= 2000),
  media_type text check (media_type is null or media_type in ('image', 'video')),
  media_path text check (media_path is null or char_length(media_path) <= 500),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.posts add column if not exists media_url text;
alter table public.posts add column if not exists media_type text;
alter table public.posts add column if not exists media_path text;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'post-media',
  'post-media',
  true,
  52428800,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'video/mp4', 'video/webm', 'video/quicktime']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create table if not exists public.enquiries (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 120),
  email text not null check (char_length(email) <= 320),
  year_level text not null check (char_length(year_level) between 2 and 80),
  message text not null default '' check (char_length(message) <= 3000),
  status text not null default 'new' check (status in ('new', 'in_progress', 'resolved')),
  created_at timestamptz not null default now()
);

create table if not exists public.staff_profiles (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 120),
  job_title text not null check (char_length(job_title) between 2 and 160),
  email text not null check (char_length(email) <= 320),
  linkedin_url text check (linkedin_url is null or char_length(linkedin_url) <= 500),
  photo_url text check (photo_url is null or char_length(photo_url) <= 2000),
  photo_path text check (photo_path is null or char_length(photo_path) <= 500),
  sort_order integer not null default 0 check (sort_order >= 0),
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.career_opportunities (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 3 and 160),
  department text not null default '' check (char_length(department) <= 120),
  location text not null default 'Waigani Heights, Port Moresby' check (char_length(location) <= 160),
  employment_type text not null default 'Full-time' check (employment_type in ('Full-time', 'Part-time', 'Contract', 'Casual', 'Internship')),
  summary text not null check (char_length(summary) between 5 and 500),
  description text not null default '' check (char_length(description) <= 12000),
  application_email text not null check (char_length(application_email) <= 320),
  application_url text check (application_url is null or char_length(application_url) <= 2000),
  closing_date date,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists posts_public_order_idx
  on public.posts (published, promoted desc, event_date desc, created_at desc);
create index if not exists posts_category_idx on public.posts (category);
create index if not exists posts_search_idx
  on public.posts using gin ((title || ' ' || summary || ' ' || body) gin_trgm_ops);
create index if not exists enquiries_status_created_idx
  on public.enquiries (status, created_at desc);
create index if not exists staff_profiles_public_order_idx
  on public.staff_profiles (published, sort_order, name);
create index if not exists career_opportunities_public_order_idx
  on public.career_opportunities (published, closing_date, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists posts_set_updated_at on public.posts;
create trigger posts_set_updated_at
before update on public.posts
for each row execute function public.set_updated_at();

drop trigger if exists staff_profiles_set_updated_at on public.staff_profiles;
create trigger staff_profiles_set_updated_at
before update on public.staff_profiles
for each row execute function public.set_updated_at();

drop trigger if exists career_opportunities_set_updated_at on public.career_opportunities;
create trigger career_opportunities_set_updated_at
before update on public.career_opportunities
for each row execute function public.set_updated_at();

drop function if exists public.search_published_posts(text);
create function public.search_published_posts(search_term text)
returns table (
  id bigint,
  title text,
  summary text,
  category text,
  event_date date,
  promoted boolean,
  media_url text,
  media_type text
)
language sql
stable
security invoker
set search_path = ''
as $$
  select p.id, p.title, p.summary, p.category, p.event_date, p.promoted,
    p.media_url, p.media_type
  from public.posts as p
  where p.published = true
    and not exists (
      select 1
      from unnest(regexp_split_to_array(btrim(search_term), '\s+')) as term
      where term <> ''
        and strpos(lower(concat_ws(' ', p.title, p.summary, p.body)), lower(term)) = 0
    )
  order by p.promoted desc, p.created_at desc
  limit 20;
$$;

revoke all on function public.search_published_posts(text) from public;
grant execute on function public.search_published_posts(text) to anon, authenticated, service_role;

alter table public.posts enable row level security;
alter table public.enquiries enable row level security;
alter table public.staff_profiles enable row level security;
alter table public.career_opportunities enable row level security;

drop policy if exists "Public can read published staff" on public.staff_profiles;
create policy "Public can read published staff"
on public.staff_profiles for select
to anon, authenticated
using (published = true);

drop policy if exists "Public can read published careers" on public.career_opportunities;
create policy "Public can read published careers"
on public.career_opportunities for select
to anon, authenticated
using (published = true);

-- Visitors may only read published posts.
drop policy if exists "Public can read published posts" on public.posts;
create policy "Public can read published posts"
on public.posts for select
to anon, authenticated
using (published = true);

-- Visitors may submit an enquiry, but cannot read enquiry records.
drop policy if exists "Public can submit enquiries" on public.enquiries;
create policy "Public can submit enquiries"
on public.enquiries for insert
to anon, authenticated
with check (status = 'new');

-- The FastAPI server uses a SUPABASE_SECRET_KEY for all database access.
-- Never expose a secret key in Vite or other browser code.
